DoxyExample: WeatherProcessor Class Reference
WeatherProcessor Class Reference
High-level application controller.
#include <WeatherProcessor.h>
Public Member Functions
WeatherProcessor ()
Default constructor.
bool initializeData (const std::string &configFilename)
Initializes the database by loading data files.
void displayWindSpeedStats () const
Menu Option 1: Displays average wind speed and stdev for a specific month/year.
void displayTemperatureStats () const
Menu Option 2: Displays average temp and stdev for each month of a specific year.
void displaySpccStats () const
Menu Option 3: Displays Sample Pearson Correlation Coefficients (sPCC) for a specific month.
void writeAllStatsToFile () const
Menu Option 4: Writes comprehensive stats (including MAD) to a CSV file.
void showMenu () const
Displays the interactive menu to the user.
Private Member Functions
std::string getMonthName (int month) const
Converts an integer month (1-12) to its string name.
bool extractMonthData (int month, int year, Vector< float > &speeds, Vector< float > &temps, Vector< float > &solar) const
Extracts validated, purely numerical data for a specific month/year.
Private Attributes
Database db
The central data storage unit.
Detailed Description
High-level application controller.
Author
Elson Ang
Date
2026
Handles user interaction, coordinates data retrieval from the Database, prepares data for the MathUtils, and formats output according to strict specifications.
Definition at line 17 of file WeatherProcessor.h.
Constructor & Destructor Documentation
WeatherProcessor()
WeatherProcessor::WeatherProcessor ()
Default constructor.
Definition at line 8 of file WeatherProcessor.cpp.
Member Function Documentation
displaySpccStats()
void WeatherProcessor::displaySpccStats () const
Menu Option 3: Displays Sample Pearson Correlation Coefficients (sPCC) for a specific month.
Definition at line 93 of file WeatherProcessor.cpp.
References MathUtils::calcPcc(), db, extractMonthData(), getMonthName(), WeatherRecord::getSolarRad(), WeatherRecord::getSpeed(), WeatherRecord::getTemp(), Vector< T >::push_back(), Database::retrieveMonthData(), and Vector< T >::size().
Referenced by showMenu().
displayTemperatureStats()
void WeatherProcessor::displayTemperatureStats () const
Menu Option 2: Displays average temp and stdev for each month of a specific year.
Definition at line 72 of file WeatherProcessor.cpp.
References MathUtils::calcMean(), MathUtils::calcStdDev(), Vector< T >::empty(), extractMonthData(), and getMonthName().
Referenced by showMenu().
displayWindSpeedStats()
void WeatherProcessor::displayWindSpeedStats () const
Menu Option 1: Displays average wind speed and stdev for a specific month/year.
Definition at line 49 of file WeatherProcessor.cpp.
References MathUtils::calcMean(), MathUtils::calcStdDev(), Vector< T >::empty(), extractMonthData(), and getMonthName().
Referenced by showMenu().
extractMonthData()
bool WeatherProcessor::extractMonthData (int month, int year, Vector< float > & speeds, Vector< float > & temps, Vector< float > & solar) const private
Extracts validated, purely numerical data for a specific month/year.
Applies the assignment 1 rules (Wind * 3.6, Solar >= 100 * (1/6) / 1000).
Definition at line 25 of file WeatherProcessor.cpp.
References db, Vector< T >::empty(), WeatherRecord::getSolarRad(), WeatherRecord::getSpeed(), WeatherRecord::getTemp(), Vector< T >::push_back(), Database::retrieveMonthData(), and Vector< T >::size().
Referenced by displaySpccStats(), displayTemperatureStats(), displayWindSpeedStats(), and writeAllStatsToFile().
getMonthName()
std::string WeatherProcessor::getMonthName (int month) const private
Converts an integer month (1-12) to its string name.
Definition at line 18 of file WeatherProcessor.cpp.
Referenced by displaySpccStats(), displayTemperatureStats(), displayWindSpeedStats(), and writeAllStatsToFile().
initializeData()
bool WeatherProcessor::initializeData (const std::string & configFilename)
Initializes the database by loading data files.
Parameters
configFilename The main data text file.
Returns
true if successful, false otherwise.
Definition at line 10 of file WeatherProcessor.cpp.
References db, and DataLoader::loadData().
Referenced by main().
showMenu()
void WeatherProcessor::showMenu () const
Displays the interactive menu to the user.
Definition at line 182 of file WeatherProcessor.cpp.
References db, Database::displayAvailableYears(), displaySpccStats(), displayTemperatureStats(), displayWindSpeedStats(), and writeAllStatsToFile().
Referenced by main().
writeAllStatsToFile()
void WeatherProcessor::writeAllStatsToFile () const
Menu Option 4: Writes comprehensive stats (including MAD) to a CSV file.
Definition at line 136 of file WeatherProcessor.cpp.
References MathUtils::calcMad(), MathUtils::calcMean(), MathUtils::calcStdDev(), MathUtils::calcSum(), Vector< T >::empty(), extractMonthData(), and getMonthName().
Referenced by showMenu().
Member Data Documentation
db
Database WeatherProcessor::db private
The central data storage unit.
Definition at line 45 of file WeatherProcessor.h.
Referenced by displaySpccStats(), extractMonthData(), initializeData(), and showMenu().
The documentation for this class was generated from the following files:
WeatherProcessor.h
WeatherProcessor.cpp