DoxyExample: Database Class Reference
Database Class Reference
Central storage and retrieval system for weather data.
#include <Database.h>
Public Member Functions
Database ()
Default Constructor.
~Database ()
Destructor. Safely deletes all heap-allocated WeatherRecords to prevent memory leaks.
bool insertRecord (WeatherRecord *record)
Inserts a dynamically allocated weather record into the database.
bool retrieveMonthData (int month, int year, Vector< WeatherRecord * > &outVector) const
Retrieves all weather records for a specific month and year.
void displayAvailableYears () const
Prints all years currently loaded in the database.
Private Member Functions
int generateKey (int month, int year) const
Helper function to generate a unique integer key for the map.
bool isDuplicate (const Vector< WeatherRecord * > &vec, const WeatherRecord *record) const
Performs a strict duplication check.
Private Attributes
std::map< int, Vector< WeatherRecord * > > dataStore
Maps a YearMonth key (e.g., 201403) to a Vector of dynamically allocated WeatherRecords.
Bst< int > loadedYears
Tracks the unique years loaded into the system. Keeps the tree shallow and perfectly balanced.
Detailed Description
Central storage and retrieval system for weather data.
Author
Elson Ang
Date
2026
This class encapsulates the STL map and the custom BST.
The std::map handles fast retrieval of data by YearMonth.
The Bst maintains a sorted record of available years, utilizing function pointers. It strictly stores pointers to dynamically allocated WeatherRecords and manages their memory.
Definition at line 21 of file Database.h.
Constructor & Destructor Documentation
Database()
Database::Database ()
Default Constructor.
Definition at line 14 of file Database.cpp.
~Database()
Database::~Database ()
Destructor. Safely deletes all heap-allocated WeatherRecords to prevent memory leaks.
Definition at line 16 of file Database.cpp.
References dataStore, and Vector< T >::size().
Member Function Documentation
displayAvailableYears()
void Database::displayAvailableYears () const
Prints all years currently loaded in the database.
Utilizes the BST's inOrder traversal via a function pointer.
Definition at line 79 of file Database.cpp.
References Bst< T >::inOrder(), loadedYears, and printYear().
Referenced by main(), and WeatherProcessor::showMenu().
generateKey()
int Database::generateKey (int month, int year) const private
Helper function to generate a unique integer key for the map.
Parameters
month The month (1-12).
year The year.
Returns
An integer formatted as YYYYMM (e.g., 201403).
Definition at line 27 of file Database.cpp.
Referenced by insertRecord(), and retrieveMonthData().
insertRecord()
bool Database::insertRecord (WeatherRecord * record)
Inserts a dynamically allocated weather record into the database.
Parameters
record Pointer to a heap-allocated WeatherRecord.
Returns
true if successful, false if a duplicate was found (in which case the pointer is deleted).
Definition at line 42 of file Database.cpp.
References dataStore, generateKey(), WeatherRecord::getDate(), Date::GetMonth(), Date::GetYear(), Bst< T >::insert(), isDuplicate(), loadedYears, and Bst< T >::search().
Referenced by DataLoader::loadData(), and main().
isDuplicate()
bool Database::isDuplicate (const Vector< WeatherRecord * > & vec, const WeatherRecord * record) const private
Performs a strict duplication check.
Parameters
vec The Vector to check against.
record The record to validate.
Returns
true if a record with the exact Date and Time already exists.
Definition at line 31 of file Database.cpp.
References Vector< T >::size().
Referenced by insertRecord().
retrieveMonthData()
bool Database::retrieveMonthData (int month, int year, Vector< WeatherRecord * > & outVector) const
Retrieves all weather records for a specific month and year.
Parameters
month The month (1-12).
year The year.
outVector The Vector to populate with matching record pointers.
Returns
true if data exists, false otherwise.
Definition at line 67 of file Database.cpp.
References dataStore, Vector< T >::empty(), and generateKey().
Referenced by WeatherProcessor::displaySpccStats(), WeatherProcessor::extractMonthData(), and main().
Member Data Documentation
dataStore
std::map<int, Vector<WeatherRecord*> > Database::dataStore private
Maps a YearMonth key (e.g., 201403) to a Vector of dynamically allocated WeatherRecords.
Definition at line 53 of file Database.h.
Referenced by insertRecord(), retrieveMonthData(), and ~Database().
loadedYears
Bst<int> Database::loadedYears private
Tracks the unique years loaded into the system. Keeps the tree shallow and perfectly balanced.
Definition at line 56 of file Database.h.
Referenced by displayAvailableYears(), and insertRecord().
The documentation for this class was generated from the following files:
Database.h
Database.cpp