DoxyExample: Time Class Reference
Time Class Reference
Represents a specific time of day.
#include <Time.h>
Public Member Functions
Time ()
Default constructor. Initializes to 00:00:00.
Time (int h, int m, int s)
Parameterized constructor.
int getHour () const
Gets the hour.
int getMinute () const
Gets the minute.
int getSecond () const
Gets the second.
bool setTime (int h, int m, int s)
Sets the time with validation.
int toSeconds () const
Converts time to total seconds since midnight for easy comparison.
bool operator== (const Time &other) const
Equality operator.
bool operator< (const Time &other) const
Less-than operator for chronological sorting.
Private Member Functions
bool isValidTime (int h, int m, int s) const
Helper to validate time components.
Private Attributes
int hour
Hour component (0-23)
int minute
Minute component (0-59)
int second
Second component (0-59)
Detailed Description
Represents a specific time of day.
Author
Elson Ang
Date
2026
Stores time in hours, minutes, and seconds. Validates input to ensure 24-hour clock rules are followed.
Definition at line 15 of file Time.h.
Constructor & Destructor Documentation
Time() [1/2]
Time::Time ()
Default constructor. Initializes to 00:00:00.
Definition at line 3 of file Time.cpp.
Time() [2/2]
Time::Time (int h, int m, int s)
Parameterized constructor.
Parameters
h Hours (0-23).
m Minutes (0-59).
s Seconds (0-59).
Definition at line 5 of file Time.cpp.
References hour, isValidTime(), minute, and second.
Member Function Documentation
getHour()
int Time::getHour () const
Gets the hour.
Returns
int Hour (0-23).
Definition at line 11 of file Time.cpp.
References hour.
Referenced by main().
getMinute()
int Time::getMinute () const
Gets the minute.
Returns
int Minute (0-59).
Definition at line 12 of file Time.cpp.
References minute.
Referenced by main().
getSecond()
int Time::getSecond () const
Gets the second.
Returns
int Second (0-59).
Definition at line 13 of file Time.cpp.
References second.
isValidTime()
bool Time::isValidTime (int h, int m, int s) const private
Helper to validate time components.
Definition at line 38 of file Time.cpp.
Referenced by setTime(), and Time().
operator<()
bool Time::operator< (const Time & other) const
Less-than operator for chronological sorting.
Definition at line 34 of file Time.cpp.
References toSeconds().
operator==()
bool Time::operator== (const Time & other) const
Equality operator.
Definition at line 30 of file Time.cpp.
References toSeconds().
setTime()
bool Time::setTime (int h, int m, int s)
Sets the time with validation.
Returns
true if valid and set, false otherwise.
Definition at line 15 of file Time.cpp.
References hour, isValidTime(), minute, and second.
toSeconds()
int Time::toSeconds () const
Converts time to total seconds since midnight for easy comparison.
Returns
int Total seconds.
Definition at line 26 of file Time.cpp.
References hour, minute, and second.
Referenced by operator<(), and operator==().
Member Data Documentation
hour
int Time::hour private
Hour component (0-23)
Definition at line 59 of file Time.h.
Referenced by getHour(), setTime(), Time(), and toSeconds().
minute
int Time::minute private
Minute component (0-59)
Definition at line 60 of file Time.h.
Referenced by getMinute(), setTime(), Time(), and toSeconds().
second
int Time::second private
Second component (0-59)
Definition at line 61 of file Time.h.
Referenced by getSecond(), setTime(), Time(), and toSeconds().
The documentation for this class was generated from the following files:
Time.h
Time.cpp