DoxyExample: WeatherRecord Class Reference
WeatherRecord Class Reference
Represents a single line of weather data.
#include <WeatherRecord.h>
Public Member Functions
WeatherRecord ()
Default constructor.
WeatherRecord (const Date &d, const Time &t, float speed, float temp, float solarRad)
Parameterized constructor.
const Date & getDate () const
Gets the Date.
const Time & getTime () const
Gets the Time.
float getSpeed () const
Gets the Wind Speed.
float getTemp () const
Gets the Ambient Temperature.
float getSolarRad () const
Gets the Solar Radiation.
bool operator< (const WeatherRecord &other) const
Compares two WeatherRecords chronologically.
bool operator== (const WeatherRecord &other) const
Checks if two WeatherRecords occurred at the exact same Date and Time.
Private Attributes
Date d
Date of the record.
Time t
Time of the record.
float speed
Wind speed in km/h.
float temp
Ambient temperature in Celsius.
float solarRad
Solar radiation in W/m2.
Detailed Description
Represents a single line of weather data.
Author
Elson Ang
Date
2026
Stores Date, Time, and meteorological readings. Implements operator overloads to facilitate duplication checks (identifying records with identical Date/Time).
Definition at line 18 of file WeatherRecord.h.
Constructor & Destructor Documentation
WeatherRecord() [1/2]
WeatherRecord::WeatherRecord ()
Default constructor.
Definition at line 4 of file WeatherRecord.cpp.
WeatherRecord() [2/2]
WeatherRecord::WeatherRecord (const Date & d, const Time & t, float speed, float temp, float solarRad)
Parameterized constructor.
Parameters
d Date of the record.
t Time of the record.
speed Wind speed in km/h.
temp Ambient temperature in degrees C.
solarRad Solar radiation in W/m2.
Definition at line 6 of file WeatherRecord.cpp.
Member Function Documentation
getDate()
const Date & WeatherRecord::getDate () const
Gets the Date.
Returns
Date object.
Definition at line 9 of file WeatherRecord.cpp.
References d.
Referenced by Database::insertRecord(), operator<(), and operator==().
getSolarRad()
float WeatherRecord::getSolarRad () const
Gets the Solar Radiation.
Returns
float solar radiation in W/m2.
Definition at line 13 of file WeatherRecord.cpp.
References solarRad.
Referenced by WeatherProcessor::displaySpccStats(), and WeatherProcessor::extractMonthData().
getSpeed()
float WeatherRecord::getSpeed () const
Gets the Wind Speed.
Returns
float wind speed in km/h.
Definition at line 11 of file WeatherRecord.cpp.
References speed.
Referenced by WeatherProcessor::displaySpccStats(), WeatherProcessor::extractMonthData(), and main().
getTemp()
float WeatherRecord::getTemp () const
Gets the Ambient Temperature.
Returns
float temperature in degrees C.
Definition at line 12 of file WeatherRecord.cpp.
References temp.
Referenced by WeatherProcessor::displaySpccStats(), WeatherProcessor::extractMonthData(), and main().
getTime()
const Time & WeatherRecord::getTime () const
Gets the Time.
Returns
Time object.
Definition at line 10 of file WeatherRecord.cpp.
References t.
Referenced by operator<(), and operator==().
operator<()
bool WeatherRecord::operator< (const WeatherRecord & other) const
Compares two WeatherRecords chronologically.
Used for sorting records in BSTs or Maps.
Definition at line 16 of file WeatherRecord.cpp.
References d, getDate(), getTime(), and t.
operator==()
bool WeatherRecord::operator== (const WeatherRecord & other) const
Checks if two WeatherRecords occurred at the exact same Date and Time.
Crucial for duplicate validation.
Definition at line 27 of file WeatherRecord.cpp.
References d, getDate(), getTime(), and t.
Member Data Documentation
d
Date WeatherRecord::d private
Date of the record.
Definition at line 58 of file WeatherRecord.h.
Referenced by getDate(), operator<(), and operator==().
solarRad
float WeatherRecord::solarRad private
Solar radiation in W/m2.
Definition at line 62 of file WeatherRecord.h.
Referenced by getSolarRad().
speed
float WeatherRecord::speed private
Wind speed in km/h.
Definition at line 60 of file WeatherRecord.h.
Referenced by getSpeed().
t
Time WeatherRecord::t private
Time of the record.
Definition at line 59 of file WeatherRecord.h.
Referenced by getTime(), operator<(), and operator==().
temp
float WeatherRecord::temp private
Ambient temperature in Celsius.
Definition at line 61 of file WeatherRecord.h.
Referenced by getTemp().
The documentation for this class was generated from the following files:
WeatherRecord.h
WeatherRecord.cpp