DoxyExample: MathUtils Class Reference
MathUtils Class Reference
Utility class for pure statistical calculations.
#include <MathUtils.h>
Static Public Member Functions
static float calcMean (const Vector< float > &data)
Calculates the arithmetic mean.
static float calcStdDev (const Vector< float > &data, float mean)
Calculates the sample standard deviation.
static float calcMad (const Vector< float > &data, float mean)
Calculates the Mean Absolute Deviation (MAD).
static float calcPcc (const Vector< float > &x, const Vector< float > &y)
Calculates the Sample Pearson Correlation Coefficient (sPCC).
static float calcSum (const Vector< float > &data)
Calculates the sum of all elements.
Detailed Description
Utility class for pure statistical calculations.
Author
Elson Ang
Date
2026
Highly cohesive and decoupled math library. It processes generic float vectors and is completely unaware of weather-specific data types.
Definition at line 14 of file MathUtils.h.
Member Function Documentation
calcMad()
float MathUtils::calcMad (const Vector< float > & data, float mean) static
Calculates the Mean Absolute Deviation (MAD).
Parameters
data Vector of floating point numbers.
mean The pre-calculated mean of the data.
Returns
float The MAD, or 0.0f if empty.
Definition at line 24 of file MathUtils.cpp.
References Vector< T >::empty(), and Vector< T >::size().
Referenced by main(), and WeatherProcessor::writeAllStatsToFile().
calcMean()
float MathUtils::calcMean (const Vector< float > & data) static
Calculates the arithmetic mean.
Parameters
data Vector of floating point numbers.
Returns
float The mean, or 0.0f if empty.
Definition at line 4 of file MathUtils.cpp.
References Vector< T >::empty(), and Vector< T >::size().
Referenced by calcPcc(), WeatherProcessor::displayTemperatureStats(), WeatherProcessor::displayWindSpeedStats(), main(), and WeatherProcessor::writeAllStatsToFile().
calcPcc()
float MathUtils::calcPcc (const Vector< float > & x, const Vector< float > & y) static
Calculates the Sample Pearson Correlation Coefficient (sPCC).
Parameters
x First dataset vector.
y Second dataset vector.
Returns
float The sPCC value between -1.0 and 1.0, or 0.0f if invalid.
Definition at line 33 of file MathUtils.cpp.
References calcMean(), and Vector< T >::size().
Referenced by WeatherProcessor::displaySpccStats(), and main().
calcStdDev()
float MathUtils::calcStdDev (const Vector< float > & data, float mean) static
Calculates the sample standard deviation.
Parameters
data Vector of floating point numbers.
mean The pre-calculated mean of the data.
Returns
float The standard deviation, or 0.0f if size < 2.
Definition at line 14 of file MathUtils.cpp.
References Vector< T >::size().
Referenced by WeatherProcessor::displayTemperatureStats(), WeatherProcessor::displayWindSpeedStats(), main(), and WeatherProcessor::writeAllStatsToFile().
calcSum()
float MathUtils::calcSum (const Vector< float > & data) static
Calculates the sum of all elements.
Parameters
data Vector of floating point numbers.
Returns
float The sum.
Definition at line 57 of file MathUtils.cpp.
References Vector< T >::size().
Referenced by WeatherProcessor::writeAllStatsToFile().
The documentation for this class was generated from the following files:
MathUtils.h
MathUtils.cpp