DoxyExample: DataLoader Class Reference
DataLoader Class Reference
Responsible for parsing CSV files and creating WeatherRecord objects.
#include <DataLoader.h>
Static Public Member Functions
static bool loadData (const std::string &configFilename, Database &db)
Reads data_source.txt and parses the target CSV files.
Static Private Member Functions
static Vector< std::string > splitString (const std::string &str, char delimiter)
Helper function to split a string by a delimiter.
Detailed Description
Responsible for parsing CSV files and creating WeatherRecord objects.
Author
Elson Ang
Date
2026
Pure low-level I/O class. It dynamically allocates memory for new records and passes the pointers to the Database for storage.
Definition at line 18 of file DataLoader.h.
Member Function Documentation
loadData()
bool DataLoader::loadData (const std::string & configFilename, Database & db) static
Reads data_source.txt and parses the target CSV files.
Parameters
configFilename The name of the text file containing the list of CSVs.
db The Database wrapper to populate.
Returns
true if at least one file loaded successfully, false otherwise.
Definition at line 17 of file DataLoader.cpp.
References Database::insertRecord(), Vector< T >::size(), and splitString().
Referenced by WeatherProcessor::initializeData().
splitString()
Vector< std::string > DataLoader::splitString (const std::string & str, char delimiter) static private
Helper function to split a string by a delimiter.
Definition at line 6 of file DataLoader.cpp.
References Vector< T >::push_back().
Referenced by loadData().
The documentation for this class was generated from the following files:
DataLoader.h
DataLoader.cpp