DoxyExample: Bst< T > Class Template Reference
Bst< T > Class Template Reference
A generic Binary Search Tree implementation.
#include <Bst.h>
Classes
struct Node
Internal structure to hold data and subtree pointers.
Public Types
typedef void(* TraversalFunction) (const T &)
Function pointer type for traversals.
Public Member Functions
Bst ()
Default constructor.
~Bst ()
Destructor. Cleans up all heap-allocated nodes.
Bst (const Bst< T > &other)
Copy constructor for deep copying.
Bst< T > & operator= (const Bst< T > &other)
Assignment operator for deep copying.
void insert (const T &item)
Inserts an item into the tree.
bool search (const T &item) const
Searches for an item in the tree.
void inOrder (TraversalFunction process) const
Performs an in-order traversal.
void preOrder (TraversalFunction process) const
Performs a pre-order traversal.
void postOrder (TraversalFunction process) const
Performs a post-order traversal.
void debugCheckInvariant () const
Debugging routine to verify the BST invariant property.
Private Member Functions
void insert (Node *&ptr, const T &item)
bool search (Node *ptr, const T &item) const
void inOrder (Node *ptr, TraversalFunction process) const
void preOrder (Node *ptr, TraversalFunction process) const
void postOrder (Node *ptr, TraversalFunction process) const
void deleteTree (Node *&ptr)
void copyTree (Node *&thisRoot, Node *sourceRoot)
bool checkInvariantHelper (Node *ptr, const T *minVal, const T *maxVal) const
Private Attributes
Node * root
Pointer to the root node of the tree.
Detailed Description
template<class T>
class Bst< T >
A generic Binary Search Tree implementation.
Author
Elson Ang
Date
2026
This template class implements a standard Binary Search Tree. It strictly utilizes raw function pointers for traversals to maintain compatibility with C++98/C++11 constraints and ensures the client receives read-only access (const T&) to preserve tree invariants.
Definition at line 19 of file Bst.h.
Member Typedef Documentation
TraversalFunction
template<class T > typedef void(* Bst< T >::TraversalFunction) (const T &)
Function pointer type for traversals.
Uses const T& so the client cannot modify the key and break the BST invariant.
Definition at line 25 of file Bst.h.
Constructor & Destructor Documentation
Bst() [1/2]
template<class T > Bst< T >::Bst
Default constructor.
Definition at line 105 of file Bst.h.
~Bst()
template<class T > Bst< T >::~Bst
Destructor. Cleans up all heap-allocated nodes.
Definition at line 108 of file Bst.h.
Bst() [2/2]
template<class T > Bst< T >::Bst (const Bst< T > & other)
Copy constructor for deep copying.
Definition at line 111 of file Bst.h.
Member Function Documentation
checkInvariantHelper()
template<class T > bool Bst< T >::checkInvariantHelper (Node * ptr, const T * minVal, const T * maxVal) const private
Definition at line 210 of file Bst.h.
copyTree()
template<class T > void Bst< T >::copyTree (Node *& thisRoot, Node * sourceRoot) private
Definition at line 120 of file Bst.h.
Referenced by Bst< int >::Bst().
debugCheckInvariant()
template<class T > void Bst< T >::debugCheckInvariant
Debugging routine to verify the BST invariant property.
Definition at line 203 of file Bst.h.
deleteTree()
template<class T > void Bst< T >::deleteTree (Node *& ptr) private
Definition at line 191 of file Bst.h.
inOrder() [1/2]
template<class T > void Bst< T >::inOrder (Node * ptr, TraversalFunction process) const private
Definition at line 158 of file Bst.h.
inOrder() [2/2]
template<class T > void Bst< T >::inOrder (TraversalFunction process) const
Performs an in-order traversal.
Parameters
process The function pointer to execute on each node's data.
Definition at line 155 of file Bst.h.
Referenced by Database::displayAvailableYears(), and main().
insert() [1/2]
template<class T > void Bst< T >::insert (const T & item)
Inserts an item into the tree.
Parameters
item The data to insert.
Definition at line 130 of file Bst.h.
Referenced by Database::insertRecord(), and main().
insert() [2/2]
template<class T > void Bst< T >::insert (Node *& ptr, const T & item) private
Definition at line 137 of file Bst.h.
operator=()
template<class T > Bst< T > & Bst< T >::operator= (const Bst< T > & other)
Assignment operator for deep copying.
Definition at line 114 of file Bst.h.
postOrder() [1/2]
template<class T > void Bst< T >::postOrder (Node * ptr, TraversalFunction process) const private
Definition at line 182 of file Bst.h.
postOrder() [2/2]
template<class T > void Bst< T >::postOrder (TraversalFunction process) const
Performs a post-order traversal.
Parameters
process The function pointer to execute on each node's data.
Definition at line 179 of file Bst.h.
preOrder() [1/2]
template<class T > void Bst< T >::preOrder (Node * ptr, TraversalFunction process) const private
Definition at line 170 of file Bst.h.
preOrder() [2/2]
template<class T > void Bst< T >::preOrder (TraversalFunction process) const
Performs a pre-order traversal.
Parameters
process The function pointer to execute on each node's data.
Definition at line 167 of file Bst.h.
search() [1/2]
template<class T > bool Bst< T >::search (const T & item) const
Searches for an item in the tree.
Parameters
item The data to search for.
Returns
true if found, false otherwise.
Definition at line 144 of file Bst.h.
Referenced by Database::insertRecord(), and main().
search() [2/2]
template<class T > bool Bst< T >::search (Node * ptr, const T & item) const private
Definition at line 147 of file Bst.h.
Member Data Documentation
root
template<class T > Node* Bst< T >::root private
Pointer to the root node of the tree.
Definition at line 87 of file Bst.h.
Referenced by Bst< int >::Bst(), and Bst< int >::operator=().
The documentation for this class was generated from the following file:
Bst.h