DoxyExample: Unit Tests/MathUtilsTest.cpp File Reference
MathUtilsTest.cpp File Reference
#include <iostream>
#include "../MathUtils.h"
#include <cmath>
Functions
bool isEqual (float a, float b)
int main ()
Function Documentation
isEqual()
bool isEqual (float a, float b)
Definition at line 8 of file MathUtilsTest.cpp.
main()
int main ()
Definition at line 12 of file MathUtilsTest.cpp.
References MathUtils::calcMad(), MathUtils::calcMean(), MathUtils::calcPcc(), MathUtils::calcStdDev(), and Vector< T >::push_back().